export const galleryItems = [
    {
    title: "Welcome to this page",
    copy: "Where I share a comprehensive collection of the resources I utilised in my studies related to data. You'll find a variety of materials, including textbooks, online courses, bootcamps, and documentaries that have significantly contributed to my understanding of data science. Additionally, I have included information about my university degrees, outlining the programs I completed and the skills I acquired throughout my academic journey. This should provide insight into both my educational background and my approach to studying data.",
    },
    {
    title: "Northumbria University",
    copy: "I am thrilled to announce that I will be starting my master’s degree in Big Data and Data Science this September 2025. This program presents an exciting opportunity for me to deepen my understanding of data analysis, machine learning, and advanced statistical methods. I look forward to engaging with industry professionals and collaborating with fellow students.",
    place: "London",
    period: "September 2025 - Ongoing",
    type: "Masters Degree",
    subject: "Big Data and Data Science",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
    {
    title: "Lorem ipsum",
    copy: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veritatis ipsum quam ullam accusantium animi. Quaerat omnis facere accusantium corrupti? Veniam optio unde iure earum dolorum voluptatibus officia molestiae incidunt veritatis.",
    director: "London",
    cinematographer: "GG",
    },
  ];
  